version: "3.9"

services:
  db:
    image: postgres:latest
    ports:
      "55432:5432"
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: ./
      dockerfile: docker/Dockerfile.api
    environment:
      - STATIC_ROOT=/opt/project/personal_finances/staticroot
    volumes:
      - ./:/opt/personal_finances
    restart: unless-stopped
    ports:
      - "5050:8000"
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/Dockerfile.frontend
    restart: unless-stopped
    ports:
      - "3050:3000"
    environment:
      - REACT_APP_APPLICATION_API=http://localhost:5050
    volumes:
      - ./frontend:/opt/src/app
      - /opt/src/app/node_modules
