version: "3.9"

services:
  db:
    image: postgres:latest
    ports:
      - "55432:5432"
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-q",
          "-d",
          "coinbook",
          "-U",
          "postgres"
        ]
      interval: 3s

  api:
    build:
      context: ./
      dockerfile: docker/Dockerfile.api
    environment:
      - STATIC_ROOT=/opt/project/coinbook/staticroot
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    restart: unless-stopped
    ports:
      - "5050:80"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/Dockerfile.frontend
    restart: unless-stopped
    ports:
      - "3050:3000"
    environment:
      - REACT_APP_APPLICATION_API=http://localhost:5050
    volumes:
      - ./frontend:/opt/src/app
      - /opt/src/app/node_modules
