FROM python:3.10-slim

RUN apt-get update && apt-get install -y python-dev libpq-dev gcc
RUN pip install pipenv

WORKDIR /opt/coinbook

COPY Pipfile Pipfile
COPY Pipfile.lock Pipfile.lock

RUN pipenv install --system --deploy

COPY . .

COPY docker/entrypoint.sh entrypoint.sh

ENTRYPOINT [ "/bin/bash", "entrypoint.sh" ]
