"""add currency to account

Revision ID: 00004
Revises: 00003
Create Date: 2022-07-29 21:41:10.414516

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "00004"
down_revision = "00003"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "currencies",
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("code", sa.String(length=5), nullable=False),
        sa.PrimaryKeyConstraint("code"),
    )
    op.create_index(op.f("ix_currencies_code"), "currencies", ["code"], unique=False)
    op.add_column("accounts", sa.Column("currency", sa.String(), nullable=True))
    op.create_foreign_key("fk_account_currency", "accounts", "currencies", ["currency"], ["code"])
    op.execute(
        "INSERT INTO currencies (name, code) VALUES ('Euro', 'EUR'), ('US Dollar', 'USD'), ('Russian Ruble', 'RUB')"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_account_currency", "accounts", type_="foreignkey")
    op.drop_column("accounts", "currency")
    op.drop_index(op.f("ix_currencies_code"), table_name="currencies")
    op.drop_table("currencies")
    # ### end Alembic commands ###
