"""update category on delete behaviour

Revision ID: 00008
Revises: 00007
Create Date: 2022-08-23 09:16:59.856262

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "00008"
down_revision = "00007"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("operations_category_id_fkey", "operations", type_="foreignkey")
    op.create_foreign_key(
        "operations_category_id_fkey", "operations", "categories", ["category_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("operations_category_id_fkey", "operations", type_="foreignkey")
    op.create_foreign_key("operations_category_id_fkey", "operations", "categories", ["category_id"], ["id"])
    # ### end Alembic commands ###
