"""add category type

Revision ID: 00006
Revises: 00005
Create Date: 2022-08-08 14:40:36.855888

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "00006"
down_revision = "00005"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    category_type = postgresql.ENUM("expense", "income", name="category_type", create_type=False)
    category_type.create(op.get_bind(), checkfirst=True)
    op.add_column("categories", sa.Column("type", category_type, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("categories", "type")
    # ### end Alembic commands ###
