# Generated by Django 3.1.5 on 2021-03-25 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_account_category_operation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
