# Generated by Django 3.1.5 on 2021-04-15 19:06

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0004_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="operations",
        ),
        migrations.AddField(
            model_name="operation",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="operations",
                to="finances.category",
            ),
        ),
    ]
