name: Deploy
on: [push]
jobs:
  Run-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pipenv
          pipenv install
      - name: Analysing the code with black
        run: |
          black . --check

      - name: Checking imports with isort
        run: |
          isort . --check-only
      
      - name: Checking with bandit
        run: |
          bandit .

      - name: Running tests
        run: |
          pytest
